name: Upload

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: wget
      run: mkdir ci-bin/ && wget -O ci-bin/calcit_runner http://repo.calcit-lang.org/binaries/linux/calcit_runner
    - name: "permission"
      run: chmod +x ci-bin/calcit_runner

    - name: "prepare modules"
      run: >
        mkdir -p ~/.config/calcit/modules/ && cd ~/.config/calcit/modules/
        && git clone https://github.com/calcit-lang/lilac.git
        && git clone https://github.com/calcit-lang/memof.git
        && git clone https://github.com/calcit-lang/calcit-test.git
        && git clone https://github.com/Respo/respo.calcit.git
        && git clone https://github.com/Respo/respo-ui.calcit.git

    - name: "compiles to js"
      run: >
        yarn
        && ./ci-bin/calcit_runner --emit-js --once --init-fn respo-router.test/run-tests --reload-fn respo-router.test/reload!
        && target=node entry=./test.js yarn webpack && node js-out/bundle.js
        && ./ci-bin/calcit_runner --emit-js --once
        && yarn && yarn vite build --base=./

    - name: Deploy to server
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.rsync_private_key}}
      with:
        flags: '-avzr --progress'
        options: ''
        ssh_options: ''
        src: 'dist/*'
        dest: 'rsync-user@tiye.me:/web-assets/repo/${{ github.repository }}'

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"
